###
#
# runs all tests and builds package
#
###

# run all changed tests: pnpm test --filter ...[master]
# run all changed builds: pnpm build --filter ...[master]

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
            
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-v3-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-v3-

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.32.4
        run_install: true

    - name: Bootstrap & build CWF
      run: pnpm run bootstrap

    # Lint all changed packages since main
    - name: Lint packages
      run: pnpm run lint -r

    # Test all changed packages and their dependents
    # https://pnpm.io/filtering#--filter-since
    - name: Run tests
      run: pnpm test:ci --filter "...[origin/main]"

    - uses: actions/upload-artifact@master
      with:
        name: cwf-web-demo
        path: packages/web-demo/dist/web-demo