###
#
# runs all tests and builds package
#
###

# run all changed tests: pnpm test --filter ...[master]
# run all changed builds: pnpm build --filter ...[master]

name: Run Build & Tests
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.0.2

    - name: Install pnpm & bootstrap cwf
      run: |
        npm i -g pnpm
        pnpm run bootstrap
