###
#
# build all packages
#
###

# run all changed builds: pnpm build --filter ...[master]

name: Build packages
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
            
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-v3-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-v3-

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.32.4
        run_install: true

    - name: Bootstrap & build CWF
      run: pnpm run bootstrap

    - uses: actions/upload-artifact@master
      with:
        name: cwf-web-demo
        path: packages/web-demo/dist/web-demo