###
#
# runs all tests in packages changed since main
#
###

name: Lint files
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-v3-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-v3-

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.32.4
        run_install: true

    - name: Install dependencies
      run: pnpm install

    # Test all changed packages and their dependents
    # https://pnpm.io/filtering#--filter-since
    - name: Lint packages
      run: pnpm run lint -r
