###
#
# Caches node_modules installed via pnpm
#
###

on:
  workflow_call:

jobs:
  cache:
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-v3-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-v3-

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.32.4
        run_install: true