name: Release packages

# Manual trigger on github
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/ceckout@v2
        with:
          fetch-depth: 0
      
      - name: Setup node
        with:
          node-version: '16'
      
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-v3-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-v3-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.x

      - name: Install & build
        run: pnpm run bootstrap

      - name: Publish to npm
        run: pnpm -r publish --dry-run

      - name: Git tag
        run: pnpm chageset tag

