name: Run tests on pull requests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: ./.github/workflows/pnpm-cache.yaml
      
      - name: Install node_modules & link packages
        run: pnpm install && pnpx lerna bootstrap

      - name: Run tests
        run: pnpm run test:ci --filter "...[origin/main]"
