name: Run lint and tests on pull requests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-v3-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-v3-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.4
          run_install: true
      
      - name: Install node_modules & link packages
        run: pnpm install && pnpx lerna bootstrap

      # Lint all changed packages
      - name: Lint packages
        run: pnpm run lint -r --filter "[origin/main]"

      # Test all changed packages and their dependents
      # https://pnpm.io/filtering#--filter-since
      - name: Run tests
        run: pnpm test:ci --filter "...[origin/main]"
