on:
  push:
  pull_request:
    branches: [ $default_branch ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    with:
      deploy: ${{ github.event_name == 'pull_request' }}
      pr_number: ${{ github.event.number }}
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}