on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  deploy:
    if: github.event_name == 'pull_request'
    needs: build
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}